version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Ci_Cd_DB   
    ports:
      - 3306:3306
    networks:
     - AppNet
     
  spring-boot:
    image: amina98/examen
    container_name: springback
    ports:
      - 8083:8083
    depends_on:
      - database
    networks:
      - AppNet 
    restart: on-failure
networks:
  AppNet:
    driver: bridge




