version: "3"
services:
  db:
    container_name: examen_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: examv2thouraya 
    restart: always
    image: mysql:latest
     ports:
      - "3306:3306"
    networks:
     - AppNet
  
 spring-boot:
    depends_on:
      - db
    container_name: springboot-app
    ports:
      - "8083:8083"
    image: amina98/examen
   
    restart: on-failure
    




